---
name: publish mmh3_unsigned
on:
  push:
    branches:
      - master

jobs:
  publish:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Python dependencies
        run: pip install -e ".[compat,dev]" cibuildwheel twine
      - name: Publish a Python distribution to PyPI
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          cibuildwheel --output-dir dist
          python setup.py sdist
          ls dist
          twine upload dist/* -u __token__ -p ${PYPI_API_TOKEN}
