---
name: mmh3_unsigned
on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Push to PyPi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Publish a Python distribution to PyPI
        uses: casperdcl/deploy-pypi@v2
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          build: true
